# Generated by Django 4.2.7 on 2024-01-06 19:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_client_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client_logo",
            name="name",
        ),
    ]
