# Generated by Django 4.2.7 on 2024-01-07 18:02

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_remove_client_logo_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=versatileimagefield.fields.VersatileImageField(
                help_text=" The recommended size is 650x450 pixels.", upload_to="blogs"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=versatileimagefield.fields.VersatileImageField(
                help_text=" The recommended size is 850x450 pixels.",
                upload_to="services",
            ),
        ),
    ]
