# Generated by Django 4.2.7 on 2024-01-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="Counter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("plus_icon", models.BooleanField(default=True)),
            ],
        ),
    ]
