# Generated by Django 4.2.7 on 2024-01-10 16:52

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0008_counter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="image",
            field=versatileimagefield.fields.VersatileImageField(
                help_text=" The recommended size is 650x450 pixels.",
                upload_to="portfolio",
            ),
        ),
    ]
