# Generated by Django 4.2.7 on 2024-01-18 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0010_main"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="main",
            options={"verbose_name": "Main", "verbose_name_plural": "Main"},
        ),
    ]
