# Generated by Django 4.2.7 on 2024-02-16 04:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0012_hireenquiry"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="portfolio",
            options={"verbose_name": "Gallery", "verbose_name_plural": "Gallery"},
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="category",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="subtitle",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="title",
        ),
    ]
