# Generated by Django 4.2.7 on 2024-02-14 16:53

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("salary", models.CharField(max_length=255)),
                ("description", tinymce.models.HTMLField()),
                ("job_expire", models.CharField(max_length=255)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("Full Time", "Full Time"),
                            ("Part Time", "Part Time"),
                            ("Internship", "Internship"),
                            ("Freelance", "Freelance"),
                            ("Work From Home", "Work From Home"),
                            ("Remote", "Remote"),
                        ],
                        default="Full Time",
                        max_length=255,
                    ),
                ),
                ("job_role", models.CharField(max_length=255)),
                ("education", models.CharField(max_length=255)),
                ("experience", models.CharField(max_length=255)),
                ("vacancies", models.IntegerField()),
            ],
        ),
    ]
