# Generated by Django 4.2.7 on 2024-02-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0002_job_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="location_embeded",
            field=models.TextField(
                blank=True,
                help_text="Copy and paste embed code from google maps",
                null=True,
            ),
        ),
    ]
